server {
    listen 80;
    server_name eos.eos-lab.net;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name eos.eos-lab.net;

    ssl_certificate /etc/letsencrypt/live/eos.eos-lab.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/eos.eos-lab.net/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    client_max_body_size 128M;
    access_log /var/log/nginx/application.access.log;
    root /var/www/html;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ ^.+\.php {
        fastcgi_pass php-fpm:9000;
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PHP_VALUE "error_log=/var/log/nginx/application_php_errors.log";
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_index index.php;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
}
